### PR TITLE
chore: Test linter config

### PR DESCRIPTION
**Pull request by oyelakinG9**
Add window popUp to the ptoject

### CODE REVIEW

**Comment by oyelakinG9** [comment]
I have conflict issues with the former pull request, so I made a new pull request to resolve the merging conflicts.

**Comment by ShoiraTa** [comment]
STATUS: CHANGES REQUIRED 🟡 
----
Hi team, 

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far. The popup behaves as expected. Kudos on your JS 👏🏻👏🏻👏🏻 
 
Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project mostly to do with the styles. 



 ## Required Changes  :recycle: 

- [x] According to project requirements, The popup follows the design for both desktop and mobile version from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, tests, margins). Please try to meet the Figma design to comply with all the requirements, currently the buttons content is not properly aligned:

Yours  | Figma
------------- | -------------
image  | image

- [x] Fonts, margins and paddinds should also match the figma design, 

Yours  | Figma
------------- | -------------
image | image

- [x] I suggest you to meet the styles in mobile view as well:

Yours  | Figma
------------- | -------------
image | !image

***
Cheers and Happy coding! :clap: :clap: :clap:

Code review by **Shoira**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oyelakinG9** [comment]
Hi @ShoiraTa  
I've modified those areas and everything Is working perfectly now.

**Review by Cathella — APPROVED** [review]
## 🟢 Status: Approved 🎉🎉

#### Hi @team ✋🏻, 

Great job implementing changes requested by the previous reviewer 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
